// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noqycfanlhunoaquryrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vcXljZmFubGh1bm9hcXVyeXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzM4NTIsImV4cCI6MjA2NDU0OTg1Mn0.jBOrgk7h301Nx0GASg7Q2wdY6bmCSPqb5zq969l_0FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});